config/routes.rb
Rails.application.routes.draw do
  resource :messages, only: [:create]

  resources :spots do
    resources :meetups
  end
  get 'meetups' => 'meetups#index_all', as: :meetups

  resource :meetup_attendees, only: [:create, :destroy]

  devise_for :users, controllers: { registrations: 'registrations' }
  get 'users/:id' => 'users#show', via: :get, as: 'show_user'

  resources :posts

  get 'welcome/index'
  root 'welcome#index'

  %w(404 422 500).each do |code|
    get code, to: 'errors#show', code: code
  end

  get 'mailbox/inbox' => 'mailbox#inbox', as: :mailbox_inbox
  get 'mailbox/sent' => 'mailbox#sent', as: :mailbox_sent
  get 'mailbox/trash' => 'mailbox#trash', as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  resources :comments, only: [:create, :destroy]

  get 'robots.:format' => 'robots#index'

end

app/models/spot.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: spots
#
#  id          :integer          not null, primary key
#  latitude    :decimal(30, 25)
#  longitude   :decimal(30, 25)
#  description :string
#  title       :string
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  traffic     :string
#  difficulty  :integer
#  slug        :string
#
# Indexes
#
#  index_spots_on_slug     (slug) UNIQUE
#  index_spots_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class Spot < ApplicationRecord
  include FriendlyId
  friendly_id :slug_candidates, use: %i[slugged finders]
  acts_as_commentable
  belongs_to :user
  has_many :posts, dependent: :destroy
  has_many :meetups, dependent: :destroy
  validates :latitude, :longitude, :title, :difficulty, :traffic, presence: true
  enum difficulty: %i[Beginner Intermediate Professional]
  validate :daily_quota, on: :create
  reverse_geocoded_by :latitude, :longitude
  after_validation :geocode

  def daily_quota
    errors.add(:spot, 'Exceeded spot limit (3) for day.') if user.username != 'Bombhills Admin' && user.spots.where(created_at: (Time.zone.now.beginning_of_day..Time.zone.now)).count > 2
  end

  def should_generate_new_friendly_id?
    title_changed?
  end

  def slug_candidates
    [
      :title,
      %i[title latitude longitude]
    ]
  end
end

app/controllers/spots_controller.rb
# frozen_string_literal: true

class SpotsController < ApplicationController
  before_action :set_spot, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[show index]
  before_action :require_permission, except: %i[show index create new]

  # GET /spots
  # GET /spots.json
  def index
    @spots = Spot.all
    gon.search = search_param_spot
    gon.spot = id_param_spot
    gon.user_signed_in = user_signed_in?
  end

  # GET /spots/1
  # GET /spots/1.json
  def show; end

  # GET /spots/new
  def new
    @spot = Spot.new
  end

  # GET /spots/1/edit
  def edit; end

  # POST /spots
  # POST /spots.json
  def create
    @spot = Spot.new(spot_params)

    respond_to do |format|
      if @spot.save
        format.html { redirect_to spots_path(id: @spot.id), notice: 'Spot was successfully created.' }
        format.json { render :show, status: :created, location: @spot }
      else
        format.html { redirect_to :spots, notice: 'Location could not be created.' }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spots/1
  # PATCH/PUT /spots/1.json
  def update
    respond_to do |format|
      if @spot.update(spot_params)
        format.html { redirect_to spots_path(id: @spot.id), notice: 'Spot was successfully updated.' }
        format.json { render :show, status: :ok, location: @spot }
      else
        format.html { render spots_path(id: @spot.id) }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spots/1
  # DELETE /spots/1.json
  def destroy
    @spot.destroy
    respond_to do |format|
      format.html { redirect_to show_user_path(current_user), notice: 'Spot was successfully destroyed' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_spot
    @spot = Spot.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def spot_params
    params.require(:spot).permit(:latitude, :longitude, :description, :title, :difficulty, :post_id, :traffic).merge(user_id: current_user.id)
  end

  def search_param_spot
    Geocoder.search(params[:search]).first if params[:search].present?
  end

  def id_param_spot
    Spot.find(params[:id]) if params.key?(:id) && Spot.where(id: params[:id]).exists?
  end

  def require_permission
    super(@spot)
  end
end

app/helpers/spots_helper.rb
# frozen_string_literal: true

module SpotsHelper
  def difficulties
    Spot.difficulties.keys.map { |x| [x, x] }
  end
end

app/views/spots/_form.html.erb
<div id="new-spot-form" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">New Spot</h4>
      </div>

      <div class="modal-body">

        <%= form_for Spot.new, html: {class:'form-horizontal'}, url: {controller: "spots", action: "create"} do |f| %>
          <div class="form-group">
              <%= f.label :title, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
              <%= f.text_field :title, class: "form-control", required: true %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :difficulty, class: "col-sm-2 control-label"%>
            <div class="col-sm-10">
              <%= f.select :difficulty, options_for_select(difficulties), {}, { class: "form-control" } %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :traffic, class: "col-sm-2 control-label"%>
            <div class="col-sm-10">
              <%= f.text_field :traffic, class: "form-control", required: true %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :description, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
              <%= f.text_area :description, class: "form-control", required: true %>
            </div>
          </div>
          <%= hidden_field_tag('spot[latitude]', 0, id: "new-latitude") %>
          <%= hidden_field_tag('spot[longitude]', 0, id: "new-longitude") %>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <%= f.submit "Submit", class: "btn btn-default" %>
            </div>
          </div>
        <% end %>

      </div>

    </div>
  </div>
</div>

app/views/spots/_form_error.html.erb
<div id="new-location-error" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Error</h4>
      </div>

      <div class="modal-body">
        <p>You must be logged in to create location.</p>
      </div>
      <div class="modal-footer">
        <%= link_to 'login', new_user_session_path, :id => 'map-error-login-btn' %>
      </div>
    </div>
  </div>
</div>

app/views/spots/_spots_modal.html.erb
<!-- Spots Modal -->
<div class="modal fade" id="spotModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document" id="userspotsmodal-dialog">
    <div class="modal-content">
      <div class="modal-body" id="spots-modal-body">
        <div id="left">
          <ul>
            <li id="spotsbutton"><span aria-hidden="true" class="glyphicon glyphicon-map-marker" style=
                "font-size: 50px;"></span></li>
            <li id="spotseditbutton"><span aria-hidden="true" class="glyphicon glyphicon-edit" style=
                "font-size: 50px;"></span></li>
          </ul>
        </div>
        <div id="right">
          <button type="button" class="close" data-dismiss="modal" style="color: #FFF;margin-bottom: 10px;">&times;</button>
          <div class="userspots">
            <% if @current_user_spots.any? %>
              <div class="form-group">
                <%= select_tag "view_delete_spot", options_for_select(@current_user_spots.map{ |s| [s.title, s.id ]}), { class: 'form-control', id: 'sel1' } %>
              </div>
              <ul>
                <li id="modal-view-spot">view</li>
              </ul>
            <% else %>
              No spots
            <% end %>
          </div>
          <div class="usersspotsedit">
            <% if @current_user_spots.any? %>
              <form id="users-spots-edit-form">
                <div class="form-group">
                  <%= select_tag "spot_id", options_for_select(@current_user_spots.map{ |s| [s.title, s.id ]}), { class: 'form-control', id: 'sel1' } %>
                </div>
                <div class="form-group">
                  <%= select_tag "difficulty", options_for_select(difficulties, @current_user_spots.first.difficulty), { class: 'form-control', id: 'sel1' } %>
                </div>
                <div class="form-group">
                  <input name="title" type="text" class="form-control" id="usr" value="<%= @current_user_spots.first.title %>" />
                </div>
                <div class="form-group">
                  <textarea name="description" class="form-control" rows="2" id="comment" placeholder="description"><%= @current_user_spots.first.description %></textarea>
                </div>
                <div class="text-center">
                  <button type="button" class="btn btn-default" id="modal-update-button">Update</button>
                  <%= button_to 'Delete', @current_user_spots.first, method: :delete, date: { confirm: 'Are you sure?' }, id: 'modal-delete-spot', class: 'btn btn-default' %>
                </div>
              </form>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/spots/edit.html.erb
<%= render 'form' %>

<p id="notice"><%= notice %></p>

<div class="meetup">

  <div class="meetup-content">
    <h1> create <br> meetup </h1>
    <p>
      <%= @spot.description %>
    </p>

     <div class="form-group">
      <label>date and time</label>
      <input type="text" class="form-control" id="usr">
      <input type="text" class="form-control" id="usr">
    </div>

    <button type="button" class="btn btn-default">Create</button>

    <ul class="edit-back">
      <li><%= link_to 'Back', spots_path %></li>
    </ul>

  </div>

</div>

app/views/spots/index.html.erb
<% title 'Spots' %>
<div class="wrapper spots-index">
  <div class="dashboard">
    <div class="nav-tools">
      <ul>
        <li id="dash-title"><%= link_to ' bombhills ', root_path, :class => 'none' %></li>
        <li id="search-li">
          <div class="input-group">
            <%= form_tag(spots_path, method: "get", id: "form", class: "form-inline") do %>
              <%= text_field_tag :search, params[:search], id: "search-input", class: "form-control", placeholder: "search" %>
              <%= submit_tag "Search", name: nil, id: "map-search-btn", class: "btn btn-default" %>
            <% end %>
          </div>
        </li>
        <li id="find-me-btn">
          <p>find me</p>
        </li>
        <%if user_signed_in? %>
          <li data-toggle="modal" data-target="#spot-modal" id="spots-modal-link">
            <p>my spots</p>
          </li>
        <% end %>
        <%if user_signed_in? %>
          <li>
            <p>
              <%= link_to ' profile ', show_user_path(current_user) %></p>
          </li>
        <%else %>
          <li>
            <p><%= link_to " login ", new_user_session_path %></p>
          </li>
        <%end %>
        <li>
          <p><%= link_to 'posts', posts_path %></p>
        </li>
        <li id="fullscreen-btn">
          <p>hide</p>
        </li>
      </ul>
    </div>
  </div>
  <div id="map-id">
    <div class="hamburger-btn">
      <span aria-hidden="true" class="glyphicon glyphicon-align-left" id="hamburger-btn"></span>
    </div>
    <div class="alert alert-info map-alert">
      <a aria-label="close" class="close" data-dismiss="alert" href="">&times;</a>
      Right-click or hold to add a location.
    </div>
  </div>
</div>

<%= render 'spots/form' %>
<% if user_signed_in? %>
  <%= render partial: 'layouts/spots_modal', locals: { user: current_user } %>
<% end %>
<%= render 'spots/form_error' %>

<!-- Modal -->
<div id="report-modal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-md">
    <%= render template: 'messages/new', locals: { subject: 'Spot Report' } %>
  </div>
</div>

app/views/spots/new.html.erb
<h1>New Spots</h1>

<%= render 'form' %>

<%= link_to 'Back', spots_path %>

app/views/spots/show.html.erb
<% title @spot.title %>
<%= render 'layouts/navbar' %>

<div class="show-spot-container">
  <div class="side-image-container random-image-<%= rand(1..5) %> hidden-xs">
  </div>

  <div class="menu-container">
    <div class="menu-child spot-info active">
      <span class="glyphicon glyphicon-pushpin"></span>
      <p>DETAILS</p>
    </div>
    <div class="menu-child spot-meetups">
      <span class="glyphicon glyphicon-user"></span>
      <p>MEETUPS</p>
    </div>
    <div class="menu-child spot-posts">
      <span class="glyphicon glyphicon-camera"></span>
      <p>POSTS</p>
    </div>
  </div>

  <div class="spot-info-container">
    <div class="spot-info-content show-spot-content" id="spot-info-content">
      <div class="content-container">
        <h1>
          <%= @spot.title %>
        </h1>
        <p>
          <%= @spot.description %>
        </p>
        <p>
          <mark>Difficulty:</mark>
          <%= @spot.difficulty %>
        </p>
        <p>
          <mark>Traffic:</mark>
          <%= @spot.traffic%>
        </p>
      </div>
      <div class="comments-container">
        <h2>
          Comments
        </h2>
        <%= react_component('Comments', { resource: JSON.parse(render(template: 'spots/show.json.jbuilder')), commentableType: 'Spot', currentUser: current_user }) %>
      </div>
    </div>

    <div class="spot-meetups-content show-spot-content" style="display:none;">
      <h1>
        Upcoming Meetups for <%= @spot.title %>
    </h1>
    <%= link_to 'All meetups', spot_meetups_path(@spot) %>
    <% if @spot.meetups.any? %>
      <div class="meetups-list">
        <% @spot.meetups.each do |meetup| %>
          <div class="meetups-list-item">
            <h2>
              <%= link_to spot_meetup_path(@spot, meetup) do %>
                <%= meetup.title %>
              <% end %>
            </h2>
            <p class="time">
              <%= distance_of_time_in_words_to_now(meetup.time) %> on <%= meetup.time.strftime("%A %B %d %Y %I:%M %p %Z") %>
            </p>
            <p class="description">
              <%= meetup.description %>
            </p>
            <% if meetup.meetup_attendees.size > 0 %>
              <p class="count">
                <%= meetup.meetup_attendees.size %> attendees
              </p>
            <% end %>
            <% unless meetup == @spot.meetups.last %>
              <hr>
            <% end %>
          </div>
        <% end %>
      </div>
    <% else %>
      <p>
        No meetups for this spot, why not create one?
      </p>
    <% end %>
  </div>

  <div class="spot-posts-content show-spot-content" style="display:none;">
    <% if @spot.posts.any? %>
      <% @spot.posts.each_slice(2) do |posts| %>
        <div class="row">

          <% posts.each do |post| %>
            <div class="col-sm-6 col-md-6">
              <div class="thumbnail">
                <% if post.type == "ImagePost" %>
                  <%= image_tag post.image.url(:medium) %>
                <% else %>
                  <%= embed post.video_url %>
                <% end %>
                <div class="caption">
                  <h3>
                    <%= link_to post_path(post) do %>
                      <%= post.title %>
                    <% end %>
                  </h3>
                  <p><%= post.description %></p>
                  <p>
                    <%= link_to 'User', show_user_path(post.user), :class => 'btn btn-primary', id: 'user-btn' %>
                    <% if post.spot %>
                      <%= link_to 'Find', spots_path(id: post.spot.id), class: 'btn btn-default' %>
                    <% end %>
                  </p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    <% else %>
      No posts
    <% end %>
  </div>
</div>