config/routes.rb
Rails.application.routes.draw do
  resource :messages, only: [:create]

  resources :spots do
    resources :meetups
  end
  get 'meetups' => 'meetups#index_all', as: :meetups

  resource :meetup_attendees, only: [:create, :destroy]

  devise_for :users, controllers: { registrations: 'registrations' }
  get 'users/:id' => 'users#show', via: :get, as: 'show_user'

  resources :posts

  get 'welcome/index'
  root 'welcome#index'

  %w(404 422 500).each do |code|
    get code, to: 'errors#show', code: code
  end

  get 'mailbox/inbox' => 'mailbox#inbox', as: :mailbox_inbox
  get 'mailbox/sent' => 'mailbox#sent', as: :mailbox_sent
  get 'mailbox/trash' => 'mailbox#trash', as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  resources :comments, only: [:create, :destroy]

  get 'robots.:format' => 'robots#index'

end

app/models/meetup.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: meetups
#
#  id          :integer          not null, primary key
#  title       :string
#  description :string
#  time        :datetime
#  spot_id     :integer
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  slug        :string
#
# Indexes
#
#  index_meetups_on_slug     (slug) UNIQUE
#  index_meetups_on_spot_id  (spot_id)
#
# Foreign Keys
#
#  fk_rails_...  (spot_id => spots.id)
#

class Meetup < ApplicationRecord
  include FriendlyId
  friendly_id :slug_candidates, use: %i[slugged finders scoped], scope: :spot
  belongs_to :spot
  belongs_to :user
  has_many :meetup_attendees, dependent: :destroy
  has_many :attending_users, through: :meetup_attendees, source: 'user'
  validates :title, :description, :time, presence: true
  validate :valid_time, on: :create
  validate :quota, on: :create

  def valid_time
    return unless time < Time.zone.now
    errors.add(:meetup, 'Cannot create meetup starting in the past')
  end

  def quota
    errors.add(:meetup, 'Exceeded meetup limit (2) for day.') unless user.meetups.where('time >= :date AND spot_id = :spot_id', date: Time.zone.now, spot_id: spot.id).count < 2
  end

  def should_generate_new_friendly_id?
    title_changed? || time_changed?
  end

  def slug_candidates
    [
      :title,
      %i[title time]
    ]
  end
end

app/controllers/meetups_controller.rb
# frozen_string_literal: true

class MeetupsController < ApplicationController
  before_action :set_meetup, only: %i[show edit update destroy]
  before_action :set_spot, except: [:index_all]
  before_action :authenticate_user!, except: %i[show index index_all]
  before_action :require_permission, except: %i[show index index_all new create]

  # GET /spots/1/meetups
  # GET /spots/1/meetups.json
  def index
    @meetups = @spot.meetups.where('time > ?', DateTime.now.getlocal)
  end

  # GET /meetups
  # GET /meetups.json
  def index_all
    @meetups = Meetup.where('time > ?', DateTime.now.getlocal).order(time: :asc)
    @meetups = @meetups.includes(:spot).references(:spots).merge(Spot.near(params[:meetup_search], 100)) if params[:meetup_search].present?
  end

  # GET /spots/1/meetups/1
  # GET /spots/1/meetups/1.json
  def show; end

  # GET /spots/1/meetups/new
  def new
    @meetup = Meetup.new(spot: @spot)
  end

  # GET /spots/1/meetups/1/edit
  def edit; end

  # POST /spots/1/meetups
  # POST /spots/1/meetups.json
  def create
    @meetup = Meetup.new(meetup_params)

    respond_to do |format|
      if @meetup.save
        format.html { redirect_to spot_meetup_path(@spot, @meetup), notice: 'Meetup was successfully created.' }
        format.json { render :show, status: :created, meetup: @meetup }
      else
        format.html { render :new }
        format.json { render json: @meetup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spots/1/meetups/1
  # PATCH/PUT /spots/1/meetups/1.json
  def update
    respond_to do |format|
      if @meetup.update(meetup_params)
        format.html { redirect_to spot_meetup_path(@spot, @meetup), notice: 'Meetup was successfully updated.' }
        format.json { render :show, status: :ok, meetup: @meetup }
      else
        format.html { render :edit }
        format.json { render json: @meetup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spots/1/meetups/1
  # DELETE /spots/1/meetups/1.json
  def destroy
    @meetup.destroy
    respond_to do |format|
      format.html { redirect_to meetups_url, notice: 'Meetup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_meetup
    @meetup = Meetup.find(params[:id])
  end

  def set_spot
    @spot = Spot.find(params[:spot_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def meetup_params
    params.require(:meetup).permit(:title, :description, :time).merge(user_id: current_user.id, spot_id: @spot.id)
  end

  def require_permission
    super(@meetup)
  end
end

app/helpers/meetups_helper.rb
# frozen_string_literal: true

module MeetupsHelper
  def user_attending_meetup?(meetup, user)
    MeetupAttendee.where(meetup: meetup, user: user).exists?
  end
end

app/views/meetups/_form.html.erb
<%= form_for([@spot, @meetup]) do |f| %>
  <% if @meetup.errors.any? %>
    <div id="error-explanation">
      <h2><%= pluralize(@meetup.errors.count, "error") %> prohibited this meetup from being saved:</h2>

      <ul>
        <% @meetup.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :time, 'Date & Time' %><br>
    <div class="form-group">
      <div class="input-group date" id="meetup-datetime-picker">
        <input type="text" id="meetup_time" class="form-control" name="meetup[time]" />
        <span class="input-group-addon">
          <span class="glyphicon glyphicon-calendar"></span>
        </span>
      </div>
    </div>
  </div>
  <div class="actions" id="new-meetup-submit">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/meetups/edit.html.erb
<%= render 'layouts/navbar' %>

<div class="meetup-form-container container">
  <h1>Editing <%= @meetup.title %> Meetup</h1>

  <%= render 'form' %>
  <p><%= button_to "Delete", spot_meetup_path(@spot, @meetup), data: { confirm: "Are you sure?", disable_with: 'Deleting' }, method: :delete, class: 'btn btn-danger' %></p>

  <%= link_to 'Show', spot_meetup_path(@spot, @meetup) %>
  <%= link_to 'Back', spot_meetups_path(@spot) %>
</div>

app/views/meetups/index.html.erb
<% title "#{@spot.title} Meetups" %>
<%= render 'layouts/navbar' %>

<div class="meetups-index container">

  <h1>Upcoming Meetups at <%= link_to @spot.title, spot_path(@spot) %></h1>

  <% if @meetups.any? %>
    <div class="meetups-list">
      <% @meetups.each do |meetup| %>
        <div class="meetups-list-item">
          <h2>
            <%= link_to spot_meetup_path(@spot, meetup) do %>
              <%= meetup.title %>
            <% end %>
          </h2>
          <p class="time">
            <%= distance_of_time_in_words_to_now(meetup.time) %> on <%= meetup.time.strftime("%A %B %d %Y %I:%M %p %Z") %>
          </p>
          <p class="description">
            <%= meetup.description %>
          </p>
          <% if meetup.meetup_attendees.size > 0 %>
            <p class="count">
              <%= meetup.meetup_attendees.size %> attendees
            </p>
          <% end %>
          <% unless meetup == @meetups.last %>
            <hr>
          <% end %>
        </div>
      <% end %>
    </div>
  <% else %>
    <p>
      No meetups for this spot, why not create one?
    </p>
  <% end %>

  <%= link_to 'Create new spot meetup', new_spot_meetup_path, class: 'btn btn-primary btn-create-meetup' %>

</div>

app/views/meetups/index_all.html.erb
<% title 'Upcoming Meetups' %>
<%= render 'layouts/navbar' %>

<div class="meetups-index-container container">

  <h1>Upcoming Meetups</h1>

  <%= form_tag(meetups_path, method: "get", id: "form", class: "form-inline") do %>
    <%= text_field_tag :meetup_search, params[:meetup_search], id: "meetup-search-input", class: "form-control", placeholder: "Search for nearby meetups" %>
    <%= submit_tag "Search", name: nil, id: "meetup-search-btn", class: "btn btn-default" %>
  <% end %>

  <% if @meetups.any? %>
    <table id="meetups-table" data-toggle="table">
      <thead>
        <tr>
          <th data-sortable="true">
            Meetup Title
          </th>
          <th data-sortable="true">
            Spot
          </th>
          <th data-sortable="true">
            Attendees
          </th>
          <th>
            When
          </th>
        </tr>
      </thead>
      <tbody>
        <% @meetups.each do |meetup| %>
          <tr class="meetup-row">
            <td>
              <%= link_to meetup.title, spot_meetup_path(meetup.spot, meetup) %>
            </td>
            <td>
              <%= link_to meetup.spot.title, spot_path(meetup.spot) %>
            </td>
            <td>
              <%= meetup.meetup_attendees.count %>
            </td>
            <td>
              <%= distance_of_time_in_words_to_now(meetup.time) %> on <%= meetup.time.strftime("%A %B %d %Y %I:%M %p %Z") %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>
      No meetups
    </p>
  <% end %>

</div>

app/views/meetups/new.html.erb
<%= render 'layouts/navbar' %>

<div class="meetup-form-container container">

  <h1>Create new Meetup for <%= @spot.title %></h1>

  <%= render 'form' %>

  <%= link_to 'Back', spot_meetups_path %>

</div>

app/views/meetups/show.html.erb
<% title @meetup.title %>
<%= render 'layouts/navbar' %>

<div class="meetup-show-container container">


  <h1>
    <%= @meetup.title %>
  </h1>

  <hr>

  <p class="description">
    <%= @meetup.description %>
  </p>

  <p>
    <strong>When:</strong>
    <%= @meetup.time.strftime("%A %B %d %Y %I:%M %p %Z")  %>
  </p>

  <p>
    <strong>Spot:</strong>
    <%= link_to @meetup.spot.title, spot_path(@meetup.spot) %>
  </p>

  <p>
    <strong>Meetup creator:</strong>
    <%= link_to @meetup.user.username, show_user_path(@meetup.user) %>

  </p>

  <p>
    <strong>Attendees:</strong>
    <%= @meetup.meetup_attendees.count %>
    <% if user_signed_in? %>
      <%= react_component('AttendMeetup', meetup: @meetup, attending: user_attending_meetup?(@meetup, current_user)) %>
    <% end %>
  </p>

  <% if @meetup.meetup_attendees.any? %>
    <%= react_component('MeetupAttendeesDropdown', attendees: @meetup.meetup_attendees.map{|ma| ma.user.username}) %>
  <% end %>

  <%= link_to 'Back', spot_meetups_path %>
  <% if can_edit(current_user, @meetup) %>
    <%= link_to 'Edit Meetup', edit_spot_meetup_path(@spot, @meetup) %>
  <% end %>

</div>