config/routes.rb
Rails.application.routes.draw do
  resource :messages, only: [:create]

  resources :spots do
    resources :meetups
  end
  get 'meetups' => 'meetups#index_all', as: :meetups

  resource :meetup_attendees, only: [:create, :destroy]

  devise_for :users, controllers: { registrations: 'registrations' }
  get 'users/:id' => 'users#show', via: :get, as: 'show_user'

  resources :posts

  get 'welcome/index'
  root 'welcome#index'

  %w(404 422 500).each do |code|
    get code, to: 'errors#show', code: code
  end

  get 'mailbox/inbox' => 'mailbox#inbox', as: :mailbox_inbox
  get 'mailbox/sent' => 'mailbox#sent', as: :mailbox_sent
  get 'mailbox/trash' => 'mailbox#trash', as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  resources :comments, only: [:create, :destroy]

  get 'robots.:format' => 'robots#index'

end

app/controllers/conversations_controller.rb
# frozen_string_literal: true

class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def new
    @param_user_id = User.find_by('username': params[:user]).id if params.key?(:user) && User.exists?(username: params[:user])
  end

  def create
    recipients = User.where(id: conversation_params[:recipients])
    conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
    flash[:success] = 'Your message was successfully sent!'
    redirect_to conversation_path(conversation)
  end

  def show
    @receipts = conversation.receipts_for(current_user)
    # mark conversation as read
    conversation.mark_as_read(current_user)
  end

  def reply
    current_user.reply_to_conversation(conversation, message_params[:body])
    flash[:notice] = 'Your reply message was successfully sent!'
    redirect_to conversation_path(conversation)
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to mailbox_inbox_path
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to mailbox_inbox_path
  end

  private

  def conversation_params
    params.require(:conversation).permit(:subject, :body, recipients: [])
  end

  def message_params
    params.require(:message).permit(:body, :subject)
  end
end

app/helpers/conversations_helper.rb
# frozen_string_literal: true

module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<div class="media">
  <div class="media-left">
    <%= link_to show_user_path(conversation.messages.last.sender) do %>
      <%= image_tag conversation.messages.last.sender.avatar.url(:thumb), class: 'media-object message-avatar' %>
    <% end %>
  </div>
  <div class="media-body">
    <h4 class="media-heading">
      <%= conversation.recipients.select { |user| user != current_user }.map(&:username).to_sentence %> <br>
      <small><b>Subject: </b><%= conversation.subject %></small><br>
      <small><b>Date: </b><%=  conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
    </h4>
    <%= truncate conversation.messages.last.body, length: 145 %>
    <% if conversation.receipts_for(current_user).any?{|r| r.is_unread? } %>
      <%= link_to "View Unread", conversation_path(conversation)  %>
    <% else %>
      <%= link_to "View", conversation_path(conversation)  %>
    <% end %>
  </div>
</div>

app/views/conversations/_form.html.erb
<%= form_for :conversation, url: :conversations, html: { class: "" } do |f| %>
  <div class="form-group">
    <%= f.label :recipients %>
    <%= f.select(:recipients, User.select{ |u| u != current_user }.collect {|p| [ p.name, p.id ] }, { selected: @param_user_id  }, { multiple: true , class: "chosen-select form-control" })%>
  </div>
  <div class="form-group">
    <%= f.label :subject %>
    <%= f.text_field :subject, placeholder: "Subject", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :message %>
    <%= f.text_area :body, class: 'form-control',placeholder: "Type your message here", rows: 4  %>
  </div>

  <%= f.submit "Send Message", class: "btn btn-success", id: "send-message-btn" %>

<% end %>

app/views/conversations/_messages.html.erb
<% @receipts.each do |receipt| %>
  <% message = receipt.message %>
  <div class="media">
    <div class="media-left">
      <!-- user avators can go here -->
      <%= link_to show_user_path(message.sender) do %>
        <%= image_tag message.sender.avatar.url(:thumb), class: 'media-object message-avatar' %>
      <% end %>
    </div>
    <div class="media-body">
      <h4 class="media-heading">
        <%= message.sender.name %> <br>
        <small><b>Subject: </b><%= message.subject %></small><br>
        <small><b>Date: </b><%=  message.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
      </h4>
      <%= message.body %>
    </div>
  </div>
<% end %>

app/views/conversations/new.html.erb
<% title 'Compose' %>
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: true } %>

app/views/conversations/show.html.erb
<% title 'Message' %>
<%= render 'layouts/navbar' %>
<div class="container conversations-container">
  <div class="row">
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-body">
          <%= render 'mailbox/folders' %>
        </div>
      </div>
    </div>
    <div class="col-md-8">
      <div class="panel panel-default">
        <div class="panel-body">
          <%= render partial: 'messages' %>
        </div>
        <div class="panel-footer">
          <!-- Reply Form -->
          <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
            <div class="form-group">
              <%= f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control" %>
            </div>
          <%= f.submit "Reply", class: 'btn btn-success pull-right' %>
          <% end %>
          <% if conversation.is_trashed?(current_user) %>
            <%= link_to 'Untrash', untrash_conversation_path(conversation), class: 'btn btn-info', method: :post %>
          <% else %>
            <%= link_to 'Move to trash', trash_conversation_path(conversation), class: 'btn btn-danger', method: :post, data: {confirm: 'Are you sure?'} %>
          <% end %>
          <div class="clearfix"></div>
        </div>
      </div>
    </div>
  </div>
</div>