config/routes.rb
Rails.application.routes.draw do
  resource :messages, only: [:create]

  resources :spots do
    resources :meetups
  end
  get 'meetups' => 'meetups#index_all', as: :meetups

  resource :meetup_attendees, only: [:create, :destroy]

  devise_for :users, controllers: { registrations: 'registrations' }
  get 'users/:id' => 'users#show', via: :get, as: 'show_user'

  resources :posts

  get 'welcome/index'
  root 'welcome#index'

  %w(404 422 500).each do |code|
    get code, to: 'errors#show', code: code
  end

  get 'mailbox/inbox' => 'mailbox#inbox', as: :mailbox_inbox
  get 'mailbox/sent' => 'mailbox#sent', as: :mailbox_sent
  get 'mailbox/trash' => 'mailbox#trash', as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  resources :comments, only: [:create, :destroy]

  get 'robots.:format' => 'robots#index'

end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index
    @posts = ImagePost.limit 3
  end
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/welcome/index.html.erb
<!-- mobile header -->
<div class="mobile-header">
  <h1> bomb<br>hills <br>  </h1>
  <ul>
    <% if user_signed_in? %>

      <li><%= link_to 'profile', show_user_path(current_user) %></li>
      <li><%= link_to 'settings', edit_user_registration_path %></li>
      <li><%= link_to "logout", destroy_user_session_path, method: :delete %></li>

    <% else %>

      <li><%= link_to " register ", new_user_registration_path %></li>
      <li><%= link_to " login ", new_user_session_path %></li>

    <% end %>
  </ul>
</div>

<!-- header -->
<div class="header-wrapper">
  <div class="header" id="header">
    <div class="navigation">
      <ul class="nav nav-pills">
        <li role="presentation" class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            <% if user_signed_in? %>
              <%= current_user.username %>
            <% else %>
              User
            <% end %>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">

            <% if user_signed_in? %>

              <li><%= link_to ' profile ', show_user_path(current_user) %></li>
              <li>
                <%= link_to mailbox_inbox_path do %>
                  inbox
                  <% if unread_messages_count > 0 %>
                    <span class="label label-danger"><%=unread_messages_count%></span>
                  <% end %>
                <% end %>
              </li>
              <li><%= link_to ' edit profile ', edit_user_registration_path %></li>
              <li><%= link_to " logout ", destroy_user_session_path, method: :delete %></li>

            <% else %>

              <li><%= link_to " register ", new_user_registration_path %></li>
              <li><%= link_to " login ", new_user_session_path %></li>

            <% end %>

          </ul>
        </li>
        <li role="presentation"><a data-toggle="modal" data-target="#contact-modal" id="contact-btn">Contact</a></li>
      </ul>
    </div>
    <div class="content">
      <h1>bombhills </h1>
      <%= link_to ' Launch ', spots_path %>
    </div>
    <div class="find">
      <%= form_tag(spots_path, method: "get", id: "form", class: "form-inline") do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], id: "search", class: "form-control", placeholder: "or search for a specific location" %>
        </div>
        <%= submit_tag "Search", name: nil, id: "search-button", class: "btn btn-default" %>
      <% end %>
    </div>
  </div>
</div>


<!-- display -->
<div class="display">
  <div class="container">
    <div class="col-xs-12 col-sm-8 col-md-8">
      <h2> lets meetup! </h2>
      <p> With us you can find new places to ride and share them with your friends! You can also create times to meetup, customize your own user profile and join our online community.  </p>
      <%= link_to 'meetup', meetups_path %>
    </div>
    <div class="col-xs-12 col-sm-4 col-md-4" id="explore-col">
      <%= image_tag("iphone.png")%>
    </div>
  </div>
</div>

<!-- user content -->
<div class="user-content">
  <h1>discover</h1>
  <p>See what our community has been up to</p>
  <div class="container" id="user-content-glyphicons">
    <div class="col-sm-4">
      <span aria-hidden="true" class=" glyphicon glyphicon-map-marker"></span>
    </div>
    <div class="col-sm-4">
      <span aria-hidden="true" class=" glyphicon glyphicon-picture"></span>
    </div>
    <div class="col-sm-4">
      <span aria-hidden="true" class=" glyphicon glyphicon-user"></span>
    </div>
  </div>
  <p id="user-content-btn"><%= link_to 'Posts', posts_path %></p>
</div>

<!-- footer -->
<div class="footer">
  <div class="container">
    <div class="col-sm-4 col-md-4">
    </div>
    <div class="col-sm-4 col-md-4">

    </div>
    <div class="col-sm-4 col-md-4">
      <h1> We're also on! </h1>
      <ul>
        <li><%= link_to "Twitter", "https://twitter.com/Bombhillstweets", :target => "_blank" %></li>
        <li><%= link_to "and Instagram", "https://www.instagram.com/bombhillspics/", :target => "_blank" %></li>
      </ul>
    </div>
  </div>
</div>

<!-- contact modal -->
<div id="contact-modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <%= render template: 'messages/new', locals: { subject: 'Contact Us' } %>
  </div>
</div>